#SPDX-License-Identifier: MIT-0
---
# tasks file for prometheus
- name: Template prometheus.yml to server
  template:
    src: prometheus.yml.j2
    dest: /home/ubuntu/prometheus-3.2.1.linux-amd64/prometheus.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  notify: Restart Prometheus

