alertmanager_targets:
  - "localhost:9093"

rule_files:
  - "alert_rules.yml"
  # - "test_rule.yml"

scrape_configs:
  - job_name: "prometheus"
    targets:
      - "localhost:9090"

  - job_name: "ELK server"
    targets:
      - "172.31.39.180:9100"

  - job_name: "jenkins server"
    targets:
      - "172.31.42.65:9100"

